snowflake:
  target: sandbox
  outputs:
    sandbox:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      # User/password auth
      user: benji
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: BENJI
      database: SANDBOX
      warehouse: HUMANS
      schema: BENJI
      threads: 1
      client_session_keep_alive: False
      query_tag:
