my-snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      threads: 1
      account: "{{ env_var('DBT_ACCOUNT'}}.{{ env_var('DBT_REGION') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      database: "{{ env_var('DBT_DATABASE') }}"
      schema: "demo"
      warehouse: "{{ env_var('DBT_WAREHOUSE') }}"
      role: "{{ env_var('DBT_USER') }}"
      query_tag: "airflow_dbt"
      client_session_keep_alive: False
